export const departments = [
  { code:"01 / HOME AFFAIRS", name:"Civil Registration and Immigration", needs:["Apply for birth, death and marriage certificates","Apply or renew national ID and passport","Track application status online"], builds:["Online application form with document upload","Citizen-facing case tracking dashboard","Fee payment gateway linked to treasury","SMS and email notification engine"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Finance and Payments",type:"purple"}] },
  { code:"02 / NAMRA", name:"Finance and Revenue Authority", needs:["File personal and business income tax returns","Pay VAT and other taxes","Apply for tax clearance certificate","Check outstanding balances"], builds:["e-Tax filing module individual and corporate","Namibia-specific tax calculation engine","Online payment with local bank integration","Digital tax clearance with QR verification","Compliance audit trail for officials"], tags:[{label:"Finance and Payments",type:"purple"},{label:"Procurement and Assets",type:"amber"}] },
  { code:"03 / HEALTH", name:"Health and Social Services", needs:["Book clinic or hospital appointments","Access personal health records","Apply for disability or social grants","Request medical reports and letters"], builds:["Appointment scheduling linked to facility slots","Secure patient record access portal","Social grant application and approval workflow","Grant payment disbursement tracking"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Finance and Payments",type:"purple"},{label:"HR and Workforce",type:"teal"}] },
  { code:"04 / EDUCATION", name:"Education, Arts and Culture", needs:["Enrol children in schools","Apply for bursaries and scholarships","Check exam results","Apply for university admission"], builds:["School enrolment portal with placement workflow","Bursary and scholarship application and scoring","Secure exam result publication portal","School fee payment module"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Finance and Payments",type:"purple"}] },
  { code:"05 / AGRICULTURE", name:"Agriculture, Water and Land Reform", needs:["Apply for communal or resettlement land","Register a farm or plot","Apply for water connection","Request agricultural subsidies and inputs"], builds:["Land application and allocation workflow","Digital land registry with plot history","Water connection request and billing","Subsidy application, approval and disbursement"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Procurement and Assets",type:"amber"},{label:"Finance and Payments",type:"purple"}] },
  { code:"06 / LABOUR", name:"Labour and Employment Relations", needs:["Register a business or employer","Apply for work permits for foreign nationals","File labour dispute complaints","Register for unemployment benefits"], builds:["Business registration intake and approval workflow","Work permit application tracking system","Labour dispute case management module","Unemployment benefit eligibility and payment"], tags:[{label:"Citizen Portal",type:"coral"},{label:"HR and Workforce",type:"teal"},{label:"Finance and Payments",type:"purple"}] },
  { code:"07 / TRADE", name:"Trade and Industrialisation", needs:["Apply for business and trading licences","Register a company","Renew licences annually","Apply for import and export permits"], builds:["Online licence application and renewal portal","Company registration database with search","Automated renewal reminders and fee collection","Digital permit and certificate generation"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Finance and Payments",type:"purple"},{label:"Procurement and Assets",type:"amber"}] },
  { code:"08 / TRANSPORT", name:"Works and Transport - Road Authority", needs:["Register or renew vehicle licence","Apply for a drivers licence","Pay traffic fines","Book driving tests"], builds:["Vehicle registration and renewal system","Driving test booking and slot management","Traffic fine payment portal with bank integration","Licence card issuance tracking"], tags:[{label:"Finance and Payments",type:"purple"},{label:"Citizen Portal",type:"coral"}] },
  { code:"09 / MUNICIPALITIES", name:"Urban and Rural Development", needs:["Apply for a residential plot or stand","Submit building plans for approval","Pay municipal rates and utility bills","Lodge service delivery complaints"], builds:["Plot application and allocation workflow","Building plan submission and approval portal","Rates and utilities billing plus online payment","Citizen complaint and feedback management"], tags:[{label:"Finance and Payments",type:"purple"},{label:"Citizen Portal",type:"coral"},{label:"Procurement and Assets",type:"amber"}] },
  { code:"10 / ENVIRONMENT", name:"Environment, Forestry and Tourism", needs:["Apply for wildlife and conservancy permits","Register hunting or tour operators","Pay national park entrance fees"], builds:["Environmental permit application and tracking","Operator and conservancy registration module","Park fee payment and e-permit issuance"], tags:[{label:"Citizen Portal",type:"coral"},{label:"Finance and Payments",type:"purple"}] },
  { code:"11 / WELFARE", name:"Gender Equality and Child Welfare", needs:["Apply for child maintenance","Report GBV cases confidentially","Apply for foster care or adoption"], builds:["Sensitive case intake and management portal","Child welfare application and approval workflow","Social worker caseload management system","Confidential reporting with case number tracking"], tags:[{label:"Citizen Portal",type:"coral"},{label:"HR and Workforce",type:"teal"}] },
]
export const priorities = [
  { tier:"p1", tierLabel:"Phase 1", title:"NamRA - Tax and Revenue", desc:"Every employed Namibian and every registered business files taxes. Currently mostly paper-based. A working e-Tax module is an immediate, measurable win for government revenue collection.", reason:"Finance module already handles VAT and complex tax rules. Namibia localisation is configuration, not a rebuild." },
  { tier:"p1", tierLabel:"Phase 1", title:"Home Affairs - IDs and Passports", desc:"The most complained-about government service in Namibia. Long queues, lost paperwork, zero status visibility. This also anchors the national identity layer everything else plugs into.", reason:"Workflow and case management tools are the exact fit. Solving this builds the identity backbone for all other services." },
  { tier:"p2", tierLabel:"Phase 2", title:"Road Authority - Licences and Fines", desc:"High transaction volume daily. Vehicle renewals, driving tests, and fines are simple and repetitive - ideal for a self-service portal. Fast to deploy, visible public impact.", reason:"Simple payment plus scheduling workflow. Builds public trust for the wider government rollout." },
  { tier:"p2", tierLabel:"Phase 2", title:"Municipalities - Rates and Utilities", desc:"Every household in Windhoek and Walvis Bay pays rates and utilities. Moving this online removes the biggest reason citizens visit a municipal office.", reason:"Billing modules are production-ready. Localise for NAD, integrate local banks, go live." },
  { tier:"p3", tierLabel:"Phase 3", title:"Education - Enrolment and Bursaries", desc:"School enrolment affects every family. Bursary applications are high-stakes and currently opaque. Digitising both improves equity and reduces corruption risk.", reason:"Once the citizen portal foundation is in from Phase 1, education is configuration on top - not a net-new build." },
  { tier:"p3", tierLabel:"Phase 3", title:"Agriculture - Land and Subsidies", desc:"Land reform is politically sensitive but digitally overdue. A transparent allocation workflow reduces disputes - a good-governance story for donor-funded projects.", reason:"Asset management and procurement modules underpin land registry. Position as a transparency tool." },
]
export const aiAgents = [
  { name:"Document Verification Agent", without:"A clerk manually opens each uploaded file, checks the ID or certificate, types the details into a system, and decides if it looks real. Takes days.", with:"The agent reads the uploaded document instantly, checks it against the national ID database, flags forgeries, and either approves or routes to a human - in seconds.", applies:["Home Affairs","Health","Labour","Welfare"] },
  { name:"Tax Calculation Agent", without:"Citizens fill in paper forms, a NamRA official checks the arithmetic, enters figures manually, and issues a clearance letter by post days later.", with:"The agent reads income data, applies Namibia tax rules automatically, calculates what is owed, and issues a QR-verified digital clearance certificate immediately.", applies:["NamRA","Trade","Labour"] },
  { name:"Case Routing Agent", without:"Every application lands in the same inbox. A supervisor manually reads each one and decides who should handle it - or it sits unread.", with:"The agent reads each new case, scores its complexity, assigns it to the right officer or auto-approves routine cases - so humans only touch cases that need them.", applies:["Home Affairs","Health","Welfare","Agriculture"] },
  { name:"Notification Agent", without:"Citizens have no idea what is happening with their application. They travel to the office to ask. The officer checks manually and calls back maybe.", with:"The agent watches every status change in real time and fires an SMS or email to the citizen the moment something moves - without any human triggering it.", applies:["All departments"] },
  { name:"Fraud Detection Agent", without:"Duplicate applications, false addresses, and forged documents go unnoticed until an audit months later - if ever.", with:"The agent cross-checks every new submission against existing records, flags duplicates and anomalies instantly, and holds suspicious cases for human review before any decision is made.", applies:["NamRA","Home Affairs","Land Reform","Trade"] },
  { name:"Land Allocation Agent", without:"Officials manually compare hundreds of applicants against available plots, cross-check eligibility rules, and make decisions that are hard to audit.", with:"The agent scores every applicant against published criteria, ranks them transparently, matches them to available plots, and generates a full audit trail of every decision.", applies:["Agriculture","Municipalities"] },
]
